PageTitleSep: #{asText " | "}
WrapText t@Text: #{t}
SubmitForm: Submit
FormMsgInvalidInteger t@Text: Invalid Integer: #{t}
FormMsgInvalidNumber t@Text: Invalid Number: #{t}
FormMsgInvalidEntry t@Text: Invalid Entry: #{t}
FormMsgInvalidUrl t@Text: Invalid URL: #{t}
FormMsgInvalidEmail t@Text: Invalid Email: #{t}
FormMsgInvalidTimeFormat: Invalid time, must be in HH:MM[:SS] format
FormMsgInvalidHour t@Text: Invalid hour: #{t}
FormMsgInvalidMinute t@Text: Invalid minute: #{t}
FormMsgInvalidSecond t@Text: Invalid second: #{t}
FormMsgInvalidDay: Invalid day, must be in YYYY-MM-DD format
FormMsgCsrfWarning: As a protection against cross-site request forgery attacks, please confirm your form submission.
FormMsgValueRequired: Value is required
FormMsgInputNotFound t@Text: Input not found: #{t}
FormMsgSelectNone: <None>
FormMsgInvalidBool t@Text: Invalid boolean: #{t}
FormMsgBoolYes: Yes
FormMsgBoolNo: No
FormMsgDelete: Delete?
