PageTitleSep: #{asText " | "}
SubmitForm: Submit
ObjectNotFoundById: Database record not found by the id
InvalidDbObjectId: Invalid database record id
FormMsgInvalidInteger t@Text: Invalid Integer: #{t}
FormMsgInvalidNumber t@Text: Invalid Number: #{t}
FormMsgInvalidEntry t@Text: Invalid Entry: #{t}
FormMsgInvalidUrl t@Text: Invalid URL: #{t}
FormMsgInvalidEmail t@Text: Invalid Email: #{t}
FormMsgInvalidTimeFormat: Invalid time, must be in HH:MM[:SS] format
FormMsgInvalidHour t@Text: Invalid hour: #{t}
FormMsgInvalidMinute t@Text: Invalid minute: #{t}
FormMsgInvalidSecond t@Text: Invalid second: #{t}
FormMsgInvalidDay: Invalid day, must be in YYYY-MM-DD format
FormMsgCsrfWarning: As a protection against cross-site request forgery attacks, please confirm your form submission.
FormMsgValueRequired: Value is required
FormMsgInputNotFound t@Text: Input not found: #{t}
FormMsgSelectNone: <None>
FormMsgInvalidBool t@Text: Invalid boolean: #{t}
FormMsgBoolYes: Yes
FormMsgBoolNo: No
FormMsgDelete: Delete?
FormMsgMustBePositive: Must be positive.
FormMsgMustNotBeNegative: Must not be negative.
Monday: Monday
Tuesday: Tuesday
Wednesday: Wednesday
Thursday: Thursday
Friday: Friday
Saturday: Saturday
Sunday: Sunday
