PageTitleSep: #{asText " | "}
WrapText t@Text: #{t}
SubmitForm: 提交
FormMsgInvalidInteger t@Text: 无效的整数: #{t}
FormMsgInvalidNumber t@Text: 无效的数字: #{t}
FormMsgInvalidEntry t@Text: 无效的条目: #{t}
FormMsgInvalidUrl t@Text: 无效的 URL: #{t}
FormMsgInvalidEmail t@Text: 无效的电子邮件地址: #{t}
FormMsgInvalidTimeFormat: 无效的时间, 必须用 HH:MM[:SS] 格式
FormMsgInvalidHour t@Text: 无效的小时: #{t}
FormMsgInvalidMinute t@Text: 无效的分钟: #{t}
FormMsgInvalidSecond t@Text: 无效的秒数: #{t}
FormMsgInvalidDay: 无效的日期, 必须用 YYYY-MM-DD 格式
FormMsgCsrfWarning: 为防止跨站请求伪造，请确认您所提交的表单数据.
FormMsgValueRequired: 必须输入
FormMsgInputNotFound t@Text: 找不到输入: #{t}
FormMsgSelectNone: <无>
FormMsgInvalidBool t@Text: 无效的布尔值: #{t}
FormMsgBoolYes: 是
FormMsgBoolNo: 否
FormMsgDelete: 删除?
FormMsgMustBePositive: 必须为正数.
FormMsgMustNotBeNegative: 不能为负数
Monday: 周一
Tuesday: 周二
Wednesday: 周三
Thursday: 周四
Friday: 周五
Saturday: 周六
Sunday: 周日
